version: "3.4"

services:
  web:
    build:
      context: .
      target: web_server
    ports:
      - target: 4200
        published: 4200
        protocol: tcp
    volumes:
      - "/app/node_modules"
      - ".:/app"

  api:
    build:
      context: .
      target: flask_api
    ports:
      - target: 8080
        published: 8080
        protocol: tcp

  cron:
    build:
      context: .
      target: cronjob
    entrypoint: [ "bash", "-c", "cron -f" ]
    volumes:
      - .:/srv/app